### ISSUE TITLE
您好，我使用keil的ac6编译工程有一些错误

### ISSUE THREAD

**Issue by LikWoody** [zlgopen/awtk-stm32h743iitx-freertos#1]
![微信截图_20210611143356](https://user-images.githubusercontent.com/11622534/121641759-2cdbca80-cac2-11eb-89a5-7d251b897aa1.png)
![微信截图_20210611143409](https://user-images.githubusercontent.com/11622534/121641760-2cdbca80-cac2-11eb-9659-7cae5586e7c6.png)

**Comment by xianjimli** [comment]
编译器不支持C++吗？是不是在设置里勾选了c99那个选项。

**Comment by LikWoody** [comment]
支持c++,不选c99的话错误更多，您有时间方便测试一下吗？

**Comment by LikWoody** [comment]
因为使用arm cortex-m33内核芯片，只能使用ac6工具链

**Comment by yanmowudi** [comment]
因为使用arm cortex-m33内核芯片，只能使用ac6工具链

**Comment by xianjimli** [comment]
Misc Controls 中加上--gnu 标志。

不要勾选 c99，否则 C++编译不了。

**Comment by xianjimli** [comment]
我没有ac6工具链。

**Comment by yanmowudi** [comment]
![Uploading 微信截图_20210611150141.png…]()
这里可以选择

**Comment by LikWoody** [comment]
![微信截图_20210611150141](https://user-images.githubusercontent.com/11622534/121644818-1899cc80-cac6-11eb-8f50-2a2e79c396bb.png)
这里可以选择

**Comment by xianjimli** [comment]
好的。我看看。

**Comment by LikWoody** [comment]
谢谢

**Comment by xianjimli** [comment]
C/C++(AC6)中把language c设为gnu99，并把--gnu去掉即可。

**Comment by xianjimli** [comment]
你参考这个文档试试：https://github.com/zlgopen/awtk/blob/master/docs/how_to_build_with_keil_ac6.md

**Comment by LikWoody** [comment]
感谢，问题解决了。祝您端午节快乐。
